from django.db import models

# Create your models here.
class TestTranslate(models.Model):
	text = models.TextField(max_length=220)
	LANGUAGES= (
   ( u'af','afrikaans'),
    (u'sq', 'albanian'),
    (u'am', 'amharic'),
   ( u'ar', 'arabic'),
   ( u'hy', 'armenian'),
    (u'az', 'azerbaijani'),
    (u'eu', 'basque'),
   ( u'be', 'belarusian'),
   ( u'bn', 'bengali'),
    (u'bs', 'bosnian'),
   ( u'bg', 'bulgarian'),
   ( u'ca', 'catalan'),
   ( u'ceb', 'cebuano'),
    (u'ny','chichewa'),
    (u'zh-cn', 'chinese (simplified)'),
    (u'zh-tw', 'chinese (traditional)'),
    (u'co', 'corsican'),
    (u'hr', 'croatian'),
    (u'cs', 'czech'),
    (u'da', 'danish'),
    (u'nl', 'dutch'),
    (u'en', 'english'),
    (u'eo', 'esperanto'),
    (u'et', 'estonian'),
    (u'tl', 'filipino'),
    (u'fi', 'finnish'),
    (u'fr', 'french'),
    (u'fy', 'frisian'),
   ( u'gl', 'galician'),
    (u'ka', 'georgian'),
    (u'de', 'german'),
    (u'el', 'greek'),
    (u'gu', 'gujarati'),
    (u'ht', 'haitian creole'),
    (u'ha', 'hausa'),
    (u'haw', 'hawaiian'),
    (u'iw','hebrew'),
    (u'hi', 'hindi'),
    (u'hmn', 'hmong'),
   ( u'hu','hungarian'),
    (u'is', 'icelandic'),
    (u'ig', 'igbo'),
    (u'id', 'indonesian'),
    (u'ga', 'irish'),
    (u'it', 'italian'),
    (u'ja', 'japanese'),
    (u'jw', 'javanese'),
    (u'kn', 'kannada'),
    (u'kk', 'kazakh'),
   ( u'km', 'khmer'),
    (u'ko', 'korean'),
    (u'ku', 'kurdish (kurmanji)'),
    (u'ky', 'kyrgyz'),
    (u'lo', 'lao'),
    (u'la', 'latin'),
    (u'lv', 'latvian'),
    (u'lt', 'lithuanian'),
    (u'lb', 'luxembourgish'),
    (u'mk', 'macedonian'),
    (u'mg', 'malagasy'),
    (u'ms', 'malay'),
    (u'ml', 'malayalam'),
    (u'mt', 'maltese'),
    (u'mi', 'maori'),
    (u'mr', 'marathi'),
    (u'mn', 'mongolian'),
    (u'my', 'myanmar (burmese)'),
    (u'ne', 'nepali'),
    (u'no', 'norwegian'),
    (u'ps', 'pashto'),
    (u'fa', 'persian'),
    (u'pl', 'polish'),
    (u'pt', 'portuguese'),
    (u'pa', 'punjabi'),
    (u'ro', 'romanian'),
    (u'ru', 'russian'),
    (u'sm', 'samoan'),
   	(u'gd', 'scots gaelic'),
    (u'sr', 'serbian'),
    (u'st', 'sesotho'),
    (u'sn', 'shona'),
    (u'sd', 'sindhi'),
    (u'si', 'sinhala'),
    (u'sk', 'slovak'),
    (u'sl', 'slovenian'),
    (u'so', 'somali'),
    (u'es', 'spanish'),
    (u'su', 'sundanese'),
    (u'sw', 'swahili'),
    (u'sv', 'swedish'),
   	(u'tg', 'tajik'),
    (u'ta', 'tamil'),
    (u'te', 'telugu'),
    (u'th', 'thai'),
    (u'tr', 'turkish'),
    (u'uk', 'ukrainian'),
    (u'ur', 'urdu'),
    (u'uz', 'uzbek'),
    (u'vi', 'vietnamese'),
    (u'cy', 'welsh'),
    (u'xh', 'xhosa'),
    (u'yi', 'yiddish'),
    (u'yo', 'yoruba'),
    (u'zu', 'zulu'),
    (u'fil', 'Filipino'),
    (u'he','Hebrew')
    )
	language         = models.CharField(choices=LANGUAGES, default='Null',blank = False,null = False,max_length=120)
	date = models.DateTimeField(auto_now_add=True)


	def __str__(self):
		return self.text 